export const VALIDATION_KEYS = {
  CLIENT_NAME_REQUIRED: "client_name_required",
  CLIENT_NAME_TOO_SHORT: "client_name_too_short",
  CLIENT_NAME_TOO_LONG: "client_name_too_long",
  IDEA_REQUIRED: "idea_required",
  IDEA_TOO_SHORT: "idea_too_short",
  IDEA_TOO_LONG: "idea_too_long",
  PLACEMENT_REQUIRED: "placement_required",
  PLACEMENT_TOO_LONG: "placement_too_long",
  SIZE_REQUIRED: "size_required",
  COLOR_REQUIRED: "color_required",
  BUDGET_TOO_LONG: "budget_too_long",
  EMAIL_INVALID: "email_invalid",
  ELIGIBILITY_REQUIRED: "eligibility_required",
  CONTACT_METHOD_REQUIRED: "contact_method_required",
  CONTACT_VALUE_REQUIRED: "contact_value_required",
  CONTACT_VALUE_INVALID: "contact_value_invalid",
  PHONE_INVALID: "phone_invalid",
  INSTAGRAM_INVALID: "instagram_invalid",
  TELEGRAM_INVALID: "telegram_invalid",
  UPLOAD_TYPE_INVALID: "upload_type_invalid",
  UPLOAD_TOO_LARGE: "upload_too_large",
  UPLOAD_TOO_MANY: "upload_too_many",
  UPLOAD_EXPIRED: "upload_expired",
  UPLOAD_INVALID: "upload_invalid",
} as const

export type ValidationKey = (typeof VALIDATION_KEYS)[keyof typeof VALIDATION_KEYS]
