-- Migration: stage6_reference_code_format
-- Stage 6 — Item 9 (folded into Item 3, task STAGE_6_TASK_03_request_form_rebuild.md)
--
-- Replaces the reference-code format generated by create_request. Old format:
-- 'REQ-' || YYYY || '-' || lpad(nextval('request_seq'), 4). New format (FS §4.6):
-- 6 characters, uppercase alphanumeric, EXCLUDING the ambiguous glyphs O/0/I/1,
-- unique per request, generated server-side on persistence.
--
-- Alphabet: ABCDEFGHJKLMNPQRSTUVWXYZ23456789 (24 letters + 8 digits = 32 chars).
-- 32^6 ≈ 1.07e9 — ample for ~5–20 requests/week. A random code is NOT monotonic
-- like the old sequence, so uniqueness is enforced by a generate-and-retry loop
-- against the existing `reference_code TEXT NOT NULL UNIQUE` constraint
-- (20260622000000_create_requests.sql:18) rather than by construction.
--
-- Signature, parameter list, return shape, and grants are UNCHANGED — only the
-- function body changes. `request_seq` is intentionally left in place (harmless;
-- no longer read by this function).
--
-- search_path: RE-ESTABLISHED by the explicit `SET search_path = public, pg_temp` clause in
-- the function definition below. CREATE OR REPLACE preserves only ownership and ACL — NOT
-- proconfig — so the SET clause here is what carries the hardening forward (the separate
-- ALTER from 20260705155244 is neither preserved nor needed once the clause is inline).
--
-- Staging note: PROJECT_DECISIONS.md ("Staging Environment") gates any create_request
-- behavior change behind a staging environment. The owner WAIVED that gate for the two
-- Stage 6 create_request recreations (this reference-code change + the Block C contact-model
-- migration) on 2026-07-15 — single prod project, test-only data. Recorded in
-- PROJECT_DECISIONS.md: the scoped exception at the "Staging Environment" gate and the
-- "Stage 6 Contact Model" decision.
--
-- Rollback: re-run 20260629154719's create_request body (the REQ-YYYY-NNNN generator),
-- then re-apply 20260705155244's ALTER ... SET search_path.

CREATE OR REPLACE FUNCTION create_request(
  p_client_submission_id  UUID,
  p_studio_id             UUID,
  p_client_name           TEXT,
  p_description           TEXT,
  p_placement             TEXT,
  p_size                  TEXT,
  p_color                 TEXT,
  p_budget                TEXT,
  p_email                 TEXT,
  p_phone                 TEXT,
  p_contact_other         TEXT,
  p_consent               BOOLEAN,
  p_files                 JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id           UUID;
  v_ref_code     TEXT;
  v_file         JSONB;
  v_alphabet     TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  v_attempt      INT;
  v_max_attempts CONSTANT INT := 20;
  v_i            INT;
  v_constraint   TEXT;
BEGIN
  -- Generate a code and INSERT; on the (rare) unique collision, regenerate and retry.
  <<insert_loop>>
  FOR v_attempt IN 1..v_max_attempts LOOP
    -- Build a 6-char code from the ambiguity-free alphabet.
    v_ref_code := '';
    FOR v_i IN 1..6 LOOP
      v_ref_code := v_ref_code || substr(v_alphabet, 1 + floor(random() * length(v_alphabet))::INT, 1);
    END LOOP;

    BEGIN
      INSERT INTO requests (
        reference_code,
        client_submission_id,
        studio_id,
        client_name,
        description,
        placement,
        size,
        color,
        budget,
        email,
        phone,
        contact_other,
        consent
      ) VALUES (
        v_ref_code,
        p_client_submission_id,
        p_studio_id,
        p_client_name,
        p_description,
        p_placement,
        p_size,
        p_color,
        p_budget,
        p_email,
        p_phone,
        p_contact_other,
        p_consent
      )
      RETURNING id INTO v_id;

      EXIT insert_loop;  -- insert succeeded
    EXCEPTION
      WHEN unique_violation THEN
        -- Two distinct causes share this error code; tell them apart by constraint name:
        --  1. requests_reference_code_* (reference_code) — regenerate and retry.
        --  2. requests_client_submission_id_key (idempotency) — a real duplicate submit;
        --     re-raise so the route's existing race-recovery path returns the existing code.
        GET STACKED DIAGNOSTICS v_constraint = CONSTRAINT_NAME;
        IF v_constraint = 'requests_client_submission_id_key' THEN
          RAISE;  -- idempotency race — not a ref-code collision; let the route recover
        END IF;
        IF v_attempt = v_max_attempts THEN
          RAISE;  -- exhausted retries on ref-code collisions — surface rather than loop forever
        END IF;
        -- otherwise: reference_code collision, loop to regenerate
    END;
  END LOOP insert_loop;

  FOR v_file IN SELECT * FROM jsonb_array_elements(p_files)
  LOOP
    INSERT INTO request_files (
      request_id,
      type,
      storage_path,
      original_name,
      mime_type,
      size
    ) VALUES (
      v_id,
      v_file->>'type',
      v_file->>'storagePath',
      v_file->>'originalName',
      v_file->>'mimeType',
      (v_file->>'size')::INTEGER
    );
  END LOOP;

  RETURN jsonb_build_object(
    'id',            v_id,
    'referenceCode', v_ref_code
  );
END;
$$;
